---
  - name: setup filebeat & nginx and send log to es
    hosts: "{{ target_hosts | default('filebeat') }}"
    gather_facts: false
    ignore_unreachable: true
    tasks:
      - name: touch access.log 
        ansible.builtin.file: 
          path: /root/access.log
          state: touch
          mode: u=rw,g=r,o=r
      - name: copy file to target host
        ansible.builtin.template:
          src: ./files/{{item}}
          dest: /root
        with_items:
          [ 'nginx.yml','filebeat.yml.j2','docker-compose.yml','index.html' ]
      - name: install filebeat & nginx via docker compose
        community.docker.docker_compose: 
          project_src: /root
          state: present
      - name: curl localhost:80
        command: curl http://localhost:80
        register: result
      - name: print result
        debug:
          msg: " {{ result }} "
